export enum ErrorCode {
  AUTH_LOGIN_FAILED_1 = 'AUTH_LOGIN_FAILED_1',
  AUTH_LOGIN_FAILED_2 = 'AUTH_LOGIN_FAILED_2',
  USER_DUP_NICKNAME = 'USER_DUP_NICKNAME',
  NOT_FOUND_USER = 'NOT_FOUND_USER',
}
